'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Button } from '@astryxdesign/core/Button'
import { ArrowUpRight, ArrowsClockwise, CaretDown, ChartLineUp, MagnifyingGlass, SignOut, X } from '@phosphor-icons/react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Company, DashboardData, Organization } from '@/lib/types'
import styles from './dashboard.module.css'

const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })
const compact = new Intl.NumberFormat('en-IN', { notation: 'compact', maximumFractionDigits: 1 })

function withContext(org: string | null, company: string | null, from = '', to = '') { const params = new URLSearchParams(); if (org) params.set('org', org); if (company) params.set('company', company); if (from) params.set('from', from); if (to) params.set('to', to); return `/?${params.toString()}` }
function Metric({ label, value, note, tone = '' }: { label: string; value: string; note: string; tone?: string }) { return <div className={styles.metric}><span>{label}</span><strong className={tone}>{value}</strong><small>{note}</small></div> }
function EmptyPanel({ title, detail }: { title: string; detail: string }) { return <div className={styles.empty}><ChartLineUp size={24} weight="light" /><strong>{title}</strong><span>{detail}</span></div> }

export function Dashboard({ organizations, companies, selectedOrganizationId, selectedCompanyId, data, from, to }: { organizations: Organization[]; companies: Company[]; selectedOrganizationId: string | null; selectedCompanyId: string | null; data: DashboardData | null; from: string; to: string }) {
  const [ledgerId, setLedgerId] = useState<string | null>(null)
  const [ledgerSearch, setLedgerSearch] = useState('')
  const [dateOpen, setDateOpen] = useState(false)
  const selectedOrg = organizations.find((org) => org.id === selectedOrganizationId)
  const selectedCompany = companies.find((company) => company.id === selectedCompanyId)
  const filteredLedgers = useMemo(() => data?.ledgers.filter((ledger) => `${ledger.name} ${ledger.parent_name ?? ''}`.toLowerCase().includes(ledgerSearch.toLowerCase())) ?? [], [data?.ledgers, ledgerSearch])
  function logout() { void fetch('/auth/signout', { method: 'POST' }).finally(() => window.location.assign('/login')) }
  return <main className={styles.shell}>
    <header className={styles.topbar}><Link href="/" className={styles.brand}><span className={styles.mark}>TB</span><span>TallyBridge</span></Link><div className={styles.topbarRight}><span className={styles.readOnly}>Read-only workspace</span><button className={styles.iconButton} onClick={logout} aria-label="Sign out"><SignOut size={18} /></button></div></header>
    <div className={styles.contextRail}><div className={styles.contextCopy}><span className={styles.eyebrow}>Reporting context</span><strong>{selectedCompany?.name ?? 'Choose a company to begin'}</strong><span>{selectedOrg?.name ?? 'Organization is required before financial data loads.'}</span></div><div className={styles.selects}><label>Organization<select value={selectedOrganizationId ?? ''} onChange={(e) => { window.location.assign(withContext(e.target.value || null, null)) }}><option value="">Select organization</option>{organizations.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select></label><label>Company<select value={selectedCompanyId ?? ''} disabled={!selectedOrganizationId} onChange={(e) => window.location.assign(withContext(selectedOrganizationId, e.target.value || null))}><option value="">{selectedOrganizationId ? 'Select company' : 'Select organization first'}</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label></div>{selectedCompanyId && <div className={styles.dateControl}><button onClick={() => setDateOpen(!dateOpen)} className={styles.dateButton} aria-expanded={dateOpen}>Period <span>{from || to ? `${from || 'Start'} — ${to || 'Today'}` : 'All time'}</span><CaretDown size={15} /></button>{dateOpen && <form className={styles.datePopover} action="/"><input type="hidden" name="org" value={selectedOrganizationId ?? ''} /><input type="hidden" name="company" value={selectedCompanyId} /><label>From<input name="from" type="date" defaultValue={from} /></label><label>To<input name="to" type="date" defaultValue={to} /></label><Button label="Apply period" type="submit" /></form>}</div>}</div>
    {!selectedCompanyId ? <section className={styles.emptyContext}><div className={styles.emptyContextRule} /><span className={styles.eyebrow}>Awaiting context</span><h1>Your numbers, in their proper context.</h1><p>Select an organization, then choose one company. TallyBridge will keep every view scoped to that choice.</p><div className={styles.steps}><span><b>01</b> Organization</span><span><b>02</b> Company</span><span><b>03</b> Executive view</span></div></section> : <>
      <section className={styles.heading}><div><span className={styles.eyebrow}>Executive overview</span><h1>{selectedCompany?.name}</h1><p>All-time accounting activity, presented with explicit debit and credit semantics.</p></div><div className={styles.syncBadge}><span className={data?.sync.status === 'error' ? styles.dotError : styles.dot} />{data?.sync.status === 'error' ? 'Sync attention needed' : data?.sync.lastSyncedAt ? `Synced ${new Date(data.sync.lastSyncedAt).toLocaleDateString('en-IN')}` : 'Sync freshness unavailable'}</div></section>
      {data?.sync.error && <div className={styles.warning} role="status"><ArrowsClockwise size={18} />{data.sync.error}</div>}
      <section className={styles.metrics}>{data ? <><Metric label="Voucher activity" value={compact.format(data.kpis.totalVouchers)} note="Included vouchers" /><Metric label="Debit movement" value={money.format(data.kpis.debit)} note="Tally deemed-positive lines" tone={styles.debit} /><Metric label="Credit movement" value={money.format(data.kpis.credit)} note="Tally deemed-negative lines" tone={styles.credit} /><Metric label="Net movement" value={money.format(data.kpis.netMovement)} note="Debit less credit" tone={styles.net} /></> : <EmptyPanel title="No overview yet" detail="Select a company with available accounting data." />}</section>
      <section className={styles.grid}><article className={`${styles.panel} ${styles.activity}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>Movement</span><h2>Debit vs credit</h2></div><span className={styles.panelHint}>Monthly roll-up</span></div>{data?.activity.length ? <><div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.activity}><defs><linearGradient id="debitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--accent)" stopOpacity={.2}/><stop offset="95%" stopColor="var(--accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--rule)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} tickFormatter={(v) => compact.format(v)} /><Tooltip formatter={(value) => money.format(Number(value))} contentStyle={{ border: '1px solid var(--rule)', borderRadius: 10, background: 'var(--paper)' }} /><Area type="monotone" dataKey="debit" name="Debit" stroke="var(--accent)" fill="url(#debitFill)" strokeWidth={2} /><Area type="monotone" dataKey="credit" name="Credit" stroke="var(--positive)" fill="none" strokeWidth={2} /></AreaChart></ResponsiveContainer></div><div className={styles.legend}><span><i className={styles.legendDebit} />Debit</span><span><i className={styles.legendCredit} />Credit</span><span className={styles.chartSummary}>Text summary: debit and credit movement by month.</span></div></> : <EmptyPanel title="No movement in this period" detail="Try a wider date range or confirm that the company has synchronized vouchers." />}</article>
        <article className={`${styles.panel} ${styles.types}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>Composition</span><h2>Voucher types</h2></div></div>{data?.voucherTypes.length ? <div className={styles.barChart}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.voucherTypes} layout="vertical" margin={{ left: 0, right: 8 }}><XAxis type="number" hide /><YAxis type="category" dataKey="type" width={78} tickLine={false} axisLine={false} tick={{ fill: 'var(--foreground)', fontSize: 11 }} /><Tooltip cursor={{ fill: 'var(--accent-soft)' }} contentStyle={{ border: '1px solid var(--rule)', borderRadius: 10, background: 'var(--paper)' }} /><Bar dataKey="count" fill="var(--accent)" radius={[0, 4, 4, 0]} barSize={16} /></BarChart></ResponsiveContainer></div> : <EmptyPanel title="No voucher mix" detail="Voucher type analysis will appear after synchronization." />}</article>
      </section>
      <section className={styles.gridLower}><article className={`${styles.panel} ${styles.recent}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>Latest entries</span><h2>Recent vouchers</h2></div><span className={styles.panelHint}>{data?.recentVouchers.length ?? 0} shown</span></div>{data?.recentVouchers.length ? <div className={styles.voucherList}>{data.recentVouchers.map((voucher) => <div className={styles.voucher} key={voucher.id}><div className={styles.voucherDate}>{new Date(voucher.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</div><div className={styles.voucherMain}><strong>{voucher.type} {voucher.number ? `· ${voucher.number}` : ''}</strong><span>{voucher.party || voucher.type}</span></div><strong className={styles.voucherAmount}>{money.format(voucher.amount)}</strong><ArrowUpRight size={17} className={styles.mutedIcon} /></div>)}</div> : <EmptyPanel title="No recent vouchers" detail="There are no included vouchers for this selection." />}</article>
        <article className={`${styles.panel} ${styles.freshness}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>Data stewardship</span><h2>Sync freshness</h2></div></div><div className={styles.freshnessBody}><div className={data?.sync.status === 'error' ? styles.freshnessIconError : styles.freshnessIcon}><ArrowsClockwise size={26} /></div><strong>{data?.sync.status === 'error' ? 'Review sync status' : data?.sync.lastSyncedAt ? 'Data is available' : 'Awaiting first sync'}</strong><p>{data?.sync.lastSyncedAt ? `Last voucher sync ${new Date(data.sync.lastSyncedAt).toLocaleString('en-IN')}.` : 'This company has not reported a successful voucher sync yet.'}</p></div></article></section>
      <section className={`${styles.panel} ${styles.ledgerPanel}`}><div className={styles.panelHeader}><div><span className={styles.eyebrow}>Chart of accounts</span><h2>Find a ledger</h2></div><span className={styles.panelHint}>Select to open detail</span></div><div className={styles.search}><MagnifyingGlass size={18} /><input value={ledgerSearch} onChange={(e) => setLedgerSearch(e.target.value)} placeholder="Search ledger or group" aria-label="Search ledger or group" /></div>{filteredLedgers.length ? <div className={styles.ledgerTable}><div className={styles.tableHead}><span>Ledger</span><span>Group</span><span>Opening</span><span>Closing</span></div>{filteredLedgers.slice(0, 80).map((ledger) => <button className={styles.ledgerRow} key={ledger.id} onClick={() => setLedgerId(ledger.id)}><span><strong>{ledger.name}</strong><small>{ledger.id.slice(0, 8)}</small></span><span>{ledger.parent_name || 'Unassigned'}</span><span>{money.format(Number(ledger.opening_balance ?? 0))}</span><span>{money.format(Number(ledger.closing_balance ?? 0))}</span></button>)}</div> : <EmptyPanel title="No ledgers found" detail={ledgerSearch ? 'Try a different search term.' : 'Chart of accounts is empty for this company.'} />}</section>
      {ledgerId && <LedgerDrawer ledger={data?.ledgers.find((ledger) => ledger.id === ledgerId)} companyId={selectedCompanyId} onClose={() => setLedgerId(null)} />}
    </>}
  </main>
}

function LedgerDrawer({ ledger, companyId, onClose }: { ledger: DashboardData['ledgers'][number] | undefined; companyId: string; onClose: () => void }) {
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(0)
  const [lines, setLines] = useState<{ voucher_date: string | null; voucher_type: string | null; voucher_number: string | null; particulars: string | null; debit_amount: number | null; credit_amount: number | null; running_balance: number | null }[]>([])
  const [hasMore, setHasMore] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { const controller = new AbortController(); fetch(`/api/ledger?company=${companyId}&ledger=${ledger?.id ?? ''}&page=${page}&search=${encodeURIComponent(query)}`, { signal: controller.signal }).then(async (response) => { const payload = await response.json() as { lines?: typeof lines; hasMore?: boolean; error?: string }; if (!response.ok) throw new Error(payload.error ?? 'Could not load ledger lines'); setLines(payload.lines ?? []); setHasMore(payload.hasMore ?? false) }).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === 'AbortError') return; setError(reason instanceof Error ? reason.message : 'Could not load ledger lines') }).finally(() => setLoading(false)); return () => controller.abort() }, [companyId, ledger?.id, page, query])
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [onClose])
  return <div className={styles.drawerBackdrop} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="ledger-title"><div className={styles.drawerHeader}><div><span className={styles.eyebrow}>Ledger detail</span><h2 id="ledger-title">{ledger?.name}</h2><span>{ledger?.parent_name || 'Unassigned group'}</span></div><button className={styles.iconButton} onClick={onClose} aria-label="Close ledger detail"><X size={19} /></button></div><div className={styles.drawerStats}><Metric label="Opening" value={money.format(Number(ledger?.opening_balance ?? 0))} note="Company opening balance" /><Metric label="Closing" value={money.format(Number(ledger?.closing_balance ?? 0))} note="Latest synchronized balance" /></div><div className={styles.search}><MagnifyingGlass size={18} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); setLoading(true); setError('') }} placeholder="Search voucher lines" aria-label="Search voucher lines" /></div>{loading ? <div className={styles.drawerNotice}>Loading page {page + 1}…</div> : error ? <div className={styles.warning} role="alert">{error}</div> : lines.length ? <div className={styles.drawerLines}>{lines.map((line, index) => <div className={styles.drawerLine} key={`${line.voucher_date}-${line.voucher_number}-${index}`}><div><strong>{line.voucher_type} {line.voucher_number ? `· ${line.voucher_number}` : ''}</strong><span>{line.voucher_date} · {line.particulars || 'No particulars'}</span></div><div><b className={styles.debit}>{line.debit_amount ? money.format(Number(line.debit_amount)) : '—'}</b><b className={styles.credit}>{line.credit_amount ? money.format(Number(line.credit_amount)) : '—'}</b></div></div>)}</div> : <div className={styles.drawerNotice}>No voucher lines match this search.</div>}<div className={styles.drawerPagination}><button onClick={() => { setPage(Math.max(0, page - 1)); setLoading(true); setError('') }} disabled={page === 0 || loading}>Previous</button><span>Page {page + 1}</span><button onClick={() => { setPage(page + 1); setLoading(true); setError('') }} disabled={!hasMore || loading}>Next</button></div><div className={styles.drawerFooter}><span>Company scoped · read-only</span><span>Allocations load on expansion</span></div></aside></div>
}
